USE `ERP_OPTICA`;

-- ENTERPRISE
INSERT INTO `ENTERPRISE` (`NAME`) VALUES ('AMVX');
INSERT INTO `PERSON` (`NAME`, `CALLNAME`, `PERSONTYPE`,`CREATEDATE`, `ENTERPRISEID`) VALUES ('AMVX', 'AMVX ENTERPRISE DEVELOPMENT SOFTWARE', 2, DATE('2022-12-15'), 1);
INSERT INTO `ENTERPRISEXPERSON` (`ENTERPRISEID`, `PERSONID`) VALUES (1, 1);
INSERT INTO `PERSONCONTACT` (`CONTACTTYPE`, `PERSONID`, `VALUE`) VALUES (2, 1, 'victorpsf2@gmail.com');
