namespace Application.Models;

public static class MultiLanguageModels
{
    public enum LanguageEnum
    {
        PTBR
    }

    public enum MessagesEnum
    {
        ERRO_INVALID_INPUT,

        ERRO_LOGIN_NAME_REQUIRED,
        ERRO_LOGIN_KEY_REQUIRED,
        ERRO_LOGIN_ENTERPRISEID_REQUIRED,

        ERRO_USER_AND_KEY_AND_CODE_INVALID,
        ERRO_USER_DONT_FOUND,
        ERRO_NOT_POSSIBLE_CREATE_CODE,
        ERRO_NAME_NOT_INFORMED,
        ERRO_NAME_RULE_LENGTH,
        ERRO_KEY_NOT_INFORMED,
        ERRO_KEY_RULE_LENGTH,
        ERRO_ENTERPRISE_NOT_INFORMED,

        ERRO_PERSON_NAME_RULE,
        ERRO_PERSON_NAME_RULE_LENGTH,
        ERRO_PERSON_CALLNAME_RULE,
        ERRO_PERSON_CALLNAME_RULE_LENGTH,
        ERRO_PERSON_BIRTHDATE_RULE,
        ERRO_PERSON_BIRTHDATE_RULE_LENGTH,
        ERRO_PERSON_CREATEDAT_RULE_LENGTH,
        ERRO_PERSON_INVALID_PERSON_TYPE,
        ERRO_PERSON_PERSONID_IS_NULLABLE_OR_ZERO,

        ERRO_DOCUMENTID_IS_NULL_OR_ZERO,
        ERRO_DOCUMENTTYPE_EXISTS,
        ERRO_DOCUMENT_NOT_EXISTS,
        ERRO_DOCUMENT_TYPE_NOT_INFORMED,
        ERRO_DOCUMENT_TYPE_INVALID,
        ERRO_DOCUMENT_VALUE_NOT_INFORMED,
        ERRO_DOCUMENT_PERSON_NOT_INFORMED,
    }
}
