USE ERP_OPTICA;

CREATE VIEW VW_ENUM$DOCUMENT_TYPE AS (
	SELECT 1 AS DOCUMENTTYPE, 'CPF' AS NAME UNION
	SELECT 2 AS DOCUMENTTYPE, 'RG' AS NAME UNION
	SELECT 3 AS DOCUMENTTYPE, 'CNH' AS NAME UNION
	SELECT 4 AS DOCUMENTTYPE, 'PIS' AS NAME UNION
	SELECT 5 AS DOCUMENTTYPE, 'CTPS' AS NAME UNION
	SELECT 6 AS DOCUMENTTYPE, 'CNPJ' AS NAME UNION
	SELECT 7 AS DOCUMENTTYPE, 'MEI' AS NAME
);