version: '3.4'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=ERPDB
      - MYSQL_DATABASE=ERP_OPTICA
    ports:
      - "3306:3306"

  authapi:
    image: auth
    environment:
      - TokenMinutes=240
      - SecretKey=f7c1532c02dca418bbb5324532004eb060422737cbe06a65ae8bbf5b3d9625d43d59e881437d50b1370e97f84ee8cd72e8cd9862b083586f756829fd1fec1a92
      - MySqlConnectionPermission=Server=db;Port=3306;User=PERMISSION_USER;Password=wO4xKwEYx4EslXeMqvNotrCcKbha5fa4d0C2pYsP4Ix6usNmzHJrGAwr/nORLrgOXarDfp6VgHqDGvlo8SpiuQ==;Database=ERP_OPTICA;
      - MySqlConnectionAuthentication=Server=db;Port=3306;User=AUTH_USER;Password=MlvdHjtdC5NXKSlf6R5o5+2+FxgYOJHk8ok0Y/GAxlfXhvdv31MKawf8/d40jdun2EB4uaYPafmBf+sC9f+xyg==;Database=ERP_OPTICA;
    ports:
      - "5100:80"
    depends_on:
      - db