namespace Authentication.Service.Repositories.Queries;

public class AuthenticateQueries
{
    public static string FindUserSql = @"
SELECT 
	A1.AUTHID       AS USERID,
    A1.NAME         AS NAME,
    A1.PASSPHRASE   AS PASSWORD,
    E1.ENTERPRISEID AS ENTERPRISEID,
    (
		SELECT P2.VALUE AS EMAIL
        FROM PERSONCONTACT P2 
        WHERE 
				P2.PERSONID = P1.PERSONID
			AND P2.CONTACTTYPE = 2
		ORDER BY P2.CONTACTID DESC
		LIMIT 1
	) AS EMAIL
FROM        AUTH            AS A1
INNER JOIN  AUTHXENTERPRISE AS A2   ON A1.AUTHID        = A2.AUTHID
INNER JOIN  ENTERPRISE      AS E1   ON E1.ENTERPRISEID  = A2.ENTERPRISEID
INNER JOIN CREDENTIAL 		AS C1 	ON C1.CREDENTIALID = A1.CREDENTIALID
INNER JOIN PERSON 			AS P1 	ON P1.PERSONID = C1.PERSONID
WHERE
		A1.DELETED_AT IS NULL
	AND A2.DELETED_AT IS NULL
    AND E1.DELETED_AT IS NULL
    AND C1.DELETED_AT IS NULL
    AND P1.DELETED_AT IS NULL
    
    AND A1.NAME = @LOGIN
    AND E1.ENTERPRISEID = @ENTERPRISEID
";

    public static string FindCodeSql = @"
SELECT 
    C1.CODEID       AS CODEID,
    C1.AUTHID       AS AUTHID,
    C1.CODE         AS CODE,
    C1.CODETYPE     AS CODETYPE,
    C1.EXPIRE_IN    AS EXPIREIN
FROM 
    CODE AS C1
WHERE
        C1.AUTHID = @AUTHID
";

    public static string FindCodeWithKeySql = @"
SELECT 
    C1.CODEID       AS CODEID,
    C1.AUTHID       AS AUTHID,
    C1.CODE         AS CODE,
    C1.CODETYPE     AS CODETYPE,
    C1.EXPIRE_IN    AS EXPIREIN
FROM 
    CODE AS C1
WHERE
        C1.CODEID = @CODEID
";

    public static string CreateCodeSql = @"
INSERT INTO CODE
    (AUTHID, CODETYPE)
VALUES 
    (@AUTHID, @CODETYPE)
";

    public static string DeleteCodeSql = @"
DELETE FROM 
    CODE AS C1
WHERE
        C1.AUTHID = @AUTHID
    AND C1.CODETYPE = @CODETYPE
";

    public static string ResendCodeSql = @"
SELECT 
	A1.AUTHID       AS USERID,
    C2.CODE			AS CODE,
    (
		SELECT P2.VALUE AS EMAIL
        FROM PERSONCONTACT P2 
        WHERE 
				P2.PERSONID = P1.PERSONID
			AND P2.CONTACTTYPE = 2
		ORDER BY P2.CONTACTID DESC
		LIMIT 1
	) AS EMAIL
FROM        AUTH            AS A1
INNER JOIN  AUTHXENTERPRISE AS A2   ON A1.AUTHID        = A2.AUTHID
INNER JOIN  ENTERPRISE      AS E1   ON E1.ENTERPRISEID  = A2.ENTERPRISEID
INNER JOIN 	CREDENTIAL 		AS C1 	ON C1.CREDENTIALID 	= A1.CREDENTIALID
INNER JOIN 	PERSON 			AS P1 	ON P1.PERSONID 		= C1.PERSONID
INNER JOIN  CODE			AS C2 	ON C2.AUTHID 		= A1.AUTHID
WHERE
		A1.DELETED_AT IS NULL
	AND A2.DELETED_AT IS NULL
    AND E1.DELETED_AT IS NULL
    AND C1.DELETED_AT IS NULL
    AND P1.DELETED_AT IS NULL
    
    AND A1.NAME         = @LOGIN
    AND E1.ENTERPRISEID = @ENTERPRISEID
    AND C2.CODETYPE     = @CODETYPE
";

    public static string EnterprisesSql = @"
SELECT 
    E.ENTERPRISEID, 
    E.NAME
FROM 
    ENTERPRISE AS E
";
}
