DROP DATABASE IF EXISTS `ERP_OPTICA`;
CREATE DATABASE IF NOT EXISTS `ERP_OPTICA`;
USE `ERP_OPTICA`;

# TABLES

CREATE TABLE IF NOT EXISTS DATABASE_PARAMETERS (
	PARAMETERID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PARAMETERNAME VARCHAR(500) NOT NULL UNIQUE,
    PARAMETERVALUE TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ENTERPRISE` (
	`ENTERPRISEID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR (200) NOT NULL UNIQUE,
    `DELETED_AT` DATETIME
);

CREATE TABLE IF NOT EXISTS `PERSON` (
	`PERSONID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(500) NOT NULL,
    `PERSONTYPE` INT(3) NOT NULL,
    `CALLNAME` VARCHAR(500),
    `CREATEDATE` DATETIME,
    `DELETED_AT` DATETIME,
  	`ENTERPRISEID` INT NOT NULL,
    
    FOREIGN KEY (`ENTERPRISEID`) REFERENCES `ENTERPRISE`(`ENTERPRISEID`)
);

CREATE TABLE IF NOT EXISTS `CREDENTIAL` (
	`CREDENTIALID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `PERSONID` BIGINT NOT NULL,
    `DELETED_AT` DATETIME,
    
    FOREIGN KEY (`PERSONID`) REFERENCES `PERSON` (`PERSONID`)
);

CREATE TABLE IF NOT EXISTS `AUTH` (
	`AUTHID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` TEXT NOT NULL, # SHA512
    `PASSPHRASE` TEXT NOT NULL, # DERIVATION KEY PBKDF2
    `CREDENTIALID` INT NOT NULL,
	`DELETED_AT` DATETIME,

    FOREIGN KEY (`CREDENTIALID`) REFERENCES `CREDENTIAL` (`CREDENTIALID`)
);

CREATE TABLE IF NOT EXISTS `PAPER` (
	`PAPERID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(500) NOT NULL,
    `ACTIVATED` TINYINT DEFAULT 0, 
    `DELETED_AT` DATETIME
);

CREATE TABLE `CONTROL` (
  `DMLTYPEID` INT NOT NULL,
  `ENTITYTYPEID` INT NOT NULL,
  `ENTITYID` INT NOT NULL,
  `USERID` INT NOT NULL,
  `CONTROLDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ENTERPRISEID` INT NOT NULL,

  FOREIGN KEY (`USERID`) REFERENCES `AUTH`(`AUTHID`),
  FOREIGN KEY (`ENTERPRISEID`) REFERENCES `ENTERPRISE`(`ENTERPRISEID`)
);

CREATE TABLE IF NOT EXISTS `CODE` (
	`CODEID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `AUTHID` INT NOT NULL,
    `CODE` VARCHAR(6),
    `CODETYPE` INT NOT NULL,
    `EXPIRE_IN` DATETIME
);

CREATE TABLE IF NOT EXISTS `ENTERPRISEXPERSON` (
	`ENTERPRISEID` INT NOT NULL,
    `PERSONID` BIGINT NOT NULL,
    
    FOREIGN KEY (`ENTERPRISEID`) REFERENCES `ENTERPRISE`(`ENTERPRISEID`),
    FOREIGN KEY (`PERSONID`) REFERENCES `PERSON`(`PERSONID`)
);

CREATE TABLE IF NOT EXISTS `AUTHXENTERPRISE` (
	`AUTHID` INT NOT NULL,
    `ENTERPRISEID` INT NOT NULL,
    `DELETED_AT` DATETIME,
    
    FOREIGN KEY (`AUTHID`) REFERENCES `AUTH`(`AUTHID`),
    FOREIGN KEY (`ENTERPRISEID`) REFERENCES `ENTERPRISE`(`ENTERPRISEID`)    
);

CREATE TABLE IF NOT EXISTS `PERMISSION` (
	`PERMISSIONID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `PERMISSIONNAME` VARCHAR(500) NOT NULL UNIQUE,
    `DELETED_AT` DATETIME
);

CREATE TABLE IF NOT EXISTS `AUTHXPAPER` (
	`AUTHID` INT NOT NULL,
    `PAPERID` INT NOT NULL,
    `DELETED_AT` DATETIME,
    
    FOREIGN KEY (`AUTHID`) REFERENCES `AUTH`(`AUTHID`),
    FOREIGN KEY (`PAPERID`) REFERENCES `PAPER`(`PAPERID`)    
);

CREATE TABLE IF NOT EXISTS `PAPERXPERMISSION` (
    `PAPERID` INT NOT NULL,
	`PERMISSIONID` INT NOT NULL,
    
    FOREIGN KEY (`PERMISSIONID`) REFERENCES `PERMISSION`(`PERMISSIONID`),
    FOREIGN KEY (`PAPERID`) REFERENCES `PAPER`(`PAPERID`)    
);

CREATE TABLE IF NOT EXISTS `PERSONDOCUMENT` (
	`DOCUMENTID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DOCUMENTTYPE` INT NOT NULL,
    `PERSONID` BIGINT NOT NULL,
    `VALUE` TEXT NOT NULL,
    
    FOREIGN KEY (`PERSONID`) REFERENCES `PERSON`(`PERSONID`)
);

CREATE TABLE IF NOT EXISTS `PERSONCONTACT` (
	`CONTACTID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CONTACTTYPE` INT NOT NULL,
    `PERSONID` BIGINT NOT NULL,
    `VALUE` TEXT NOT NULL,

    FOREIGN KEY (`PERSONID`) REFERENCES `PERSON`(`PERSONID`)
);

CREATE TABLE IF NOT EXISTS `PERSONADDRESS` (
	`ADDRESSID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ADDRESSTYPE` INT NOT NULL,
    `PERSONID` BIGINT NOT NULL,
    `VALUE` TEXT NOT NULL,

    FOREIGN KEY (`PERSONID`) REFERENCES `PERSON`(`PERSONID`)
);

# END TABLES;

# PROCEDURES

DELIMITER $$

CREATE PROCEDURE GET_INTERVAL_SECCONDS_TO_CODE (OUT SECCONDS INT) 

BEGIN
	DECLARE _SECCONDS INT;
	SELECT CAST(DBP.PARAMETERVALUE AS UNSIGNED INT) INTO _SECCONDS
    FROM DATABASE_PARAMETERS DBP 
    WHERE DBP.PARAMETERNAME = 'CODE_TABLE_INTERVAL_EXPIRE' LIMIT 1;
    
	SET SECCONDS = _SECCONDS;
END;

CREATE PROCEDURE GET_CODE_AND_EXPIRETIME_TO_TABLE_CODE (OUT CODE INT, OUT EXPIRE_IN DATETIME)

BEGIN
    DECLARE _CODE INT DEFAULT 0;
    DECLARE _EXPIRE_IN DATETIME;
    DECLARE SECCONDS INT;
    
    CALL GET_INTERVAL_SECCONDS_TO_CODE(@SECCONDS);
    SELECT @SECCONDS INTO SECCONDS;

    WHILE _CODE < 100000 OR _CODE > 999999 DO
        SELECT 
            FLOOR(
                RAND() * 1000000
            ),
            DATE_ADD(
                CURRENT_TIMESTAMP,
                INTERVAL SECCONDS SECOND
            )

            INTO _CODE, _EXPIRE_IN;
    END WHILE;

    SET CODE = _CODE;
    SET EXPIRE_IN = _EXPIRE_IN;
END;

CREATE PROCEDURE CHANGE_EXPIRE_CODES ()

BEGIN 
    DECLARE DONE INT DEFAULT FALSE;
    DECLARE CODEIDS CURSOR 
        FOR SELECT C.CODEID
            FROM CODE AS C
            WHERE C.EXPIRE_IN <= CURRENT_TIMESTAMP;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;

    OPEN CODEIDS;

    REMOVE_LOOP: LOOP
        IF DONE THEN LEAVE REMOVE_LOOP; END IF;

        BEGIN
            DECLARE CODEID BIGINT;
            FETCH CODEIDS INTO CODEID;

            CALL GET_CODE_AND_EXPIRETIME_TO_TABLE_CODE(@CODE, @EXPIREIN);
            UPDATE CODE C
                SET C.CODE = (SELECT @CODE),
                    C.EXPIRE_IN = (SELECT @EXPIREIN)
            WHERE C.CODEID = CODEID;
        END;
    END LOOP;

    CLOSE CODEIDS;
END;

$$ DELIMITER ;

# END PROCEDURES

# TRIGGER 

DELIMITER //

CREATE TRIGGER SET_CODE_AND_EXPIRETIME BEFORE INSERT ON CODE FOR EACH ROW

BEGIN 
	CALL GET_CODE_AND_EXPIRETIME_TO_TABLE_CODE(@CODE, @EXPIREIN);
    
    SET NEW.CODE = (SELECT @CODE);
    SET NEW.EXPIRE_IN = (SELECT @EXPIREIN);
END;

// DELIMITER ;

# END TRIGGER

CREATE EVENT CHANGE_EXPIRECODES ON SCHEDULE EVERY 4 MINUTE DO CALL CHANGE_EXPIRE_CODES();

# SEED

INSERT INTO `DATABASE_PARAMETERS` (`PARAMETERNAME`, `PARAMETERVALUE`) VALUES ('CODE_TABLE_INTERVAL_EXPIRE', '120');
INSERT INTO `ENTERPRISE` (`NAME`) VALUES ('ADMIN');
INSERT INTO `PERSON` (`NAME`, `CALLNAME`, `PERSONTYPE`,`CREATEDATE`, `ENTERPRISEID`) VALUES ('AMVX', 'AMVX ENTERPRISE DEVELOPMENT SOFTWARE', 2, DATE('2022-12-15'), 1);
INSERT INTO `PERSON` (`NAME`, `PERSONTYPE`,`CREATEDATE`, `ENTERPRISEID`) VALUES ('JOÃO VICTOR PALMEIRA DA SILVA FERREIRA', 1, DATE('1997-06-10'), 1);
INSERT INTO `ENTERPRISEXPERSON` (`ENTERPRISEID`, `PERSONID`) VALUES (1, 1);
INSERT INTO `PERSONCONTACT` (`CONTACTTYPE`, `PERSONID`, `VALUE`) VALUES (2, 2, 'victorpsf2@hotmail.com');
INSERT INTO `CREDENTIAL` (`PERSONID`) VALUES (2);
INSERT INTO `PERMISSION` (`PERMISSIONNAME`) VALUES ('ACCESSACCOUNTPERMISSION'), ('CREATEACCOUNTPERMISSION'), ('UPDATEACCOUNTPERMISSION'), ('REMOVEACCOUNTPERMISSION'), ('ACCESSPERSONJURIDICAL'), ('CREATEPERSONJURIDICAL'), ('UPDATEPERSONJURIDICAL'), ('REMOVEPERSONJURIDICAL'), ('ACCESSPERSONPHYSICAL'), ('CREATEPERSONPHYSICAL'), ('UPDATEPERSONPHYSICAL'), ('REMOVEPERSONPHYSICAL'), ('ACCESSCLIENT'), ('CREATECLIENT'), ('UPDATECLIENT'), ('REMOVECLIENT'), ('ACCESSEMPLOYEE'), ('CREATEEMPLOYEE'), ('UPDATEEMPLOYEE'), ('REMOVEEMPLOYEE'), ('ACCESSENTERPRISE'), ('CREATEENTERPRISE'), ('UPDATEENTERPRISE'), ('REMOVEENTERPRISE'), ('ACCESSDOCUMENT'), ('CREATEDOCUMENT'), ('UPDATEDOCUMENT'), ('REMOVEDOCUMENT'), ('ACCESSCONTACT'), ('CREATECONTACT'), ('UPDATECONTACT'), ('REMOVECONTACT'), ('ACCESSADDRESS'), ('CREATEADDRESS'), ('UPDATEADDRESS'), ('REMOVEADDRESS');
INSERT INTO `AUTH` (`NAME`, `PASSPHRASE`, `CREDENTIALID`) VALUES ('kzzDxfrtyORs2u4aoIPPsFHaXPPdipc//o6uGSLZj8MNgqa0ORz9nR3VbxPedsKi+NJtnh21Z0o5aSYqjzCByQ==', 'rrl8NfRYMHMukImOri1r37AFTxFxm8dc2eiEtMKimFp3rFqI3dhZ/bM9ODEBdkCRPREDeThhSNix2WGBqcK6otw9n5wtR7EbV/FJuyeo5JfNFAdNs7Ym0G1hLtTW1Rz7eFIj1te/kSsoZoxCjnZOXTf/2EREzKl3ilIHgyfGXd81XkUSbszsR3fUpfPgZciuTXZU6y4wYpNPZAIWR5uIFuQh1bGjz+jLRoXbWc0b52ubY75dIPT00MNQN8iiBPslOi1AOoB3yk4US5RQ/x1VTey4Qwwk0W+Jr3jc6KIOwz5s2YG10+pfED4XP2mbZGn7nqc132C/EYiHixMnziwa7PmHXejaq3QsmzHxEqAsOLcae2IHEE1B7PEP0XN8OpWHVnDTi+5yOcYmHLiI1+E47n/i69M0/Yu9Jh2x1a+vqaGJQyKjGhnq6XJvYsdLJ+mORbRj76WB78UeuIWG30urlR0+FrfIS8Z81olJOMBZKQAk3V53FE99CAhXNzKKfYWGaoQp9EnhvC10hxJMprCULiFa69B82FrbcHyg0p1KkEkc/3eoS6v3+cLvjDWiwOIoEUUESYYdim3RdpfsgXwIRSCsxx2jA/sG98a886Lh/5nrF+4gEe1QhFBoxl9VH1DY2hQCHBO7cf5xOiKPwzVc8vcisP7O4+e4M3Y2nfT9nKOkWseQbrKPjKxOL8e0btK+UGcQSYL8gIVyBY0e29hjKIoVXyPcpo0LKrdugabrGVdGvndQbJ53p6TUwGOcu/hkftF3s/F/IBZV6WD/o5Ke0CEnZeEBbxSNIYVvtQLtb/nU4cXyAPb5bU4fbqOTRjlUWcXjm1cYb2VtirOLpgTkg1mL7J/edS2+f+Ot3TsQS4KMrgFdKsLIm6OR5Qg61t/0odq+l9jilUNFpy3St8VKxyV2zNgA1Xrpp1BWwy4Vfqr2nblgOQbG7Y0SH9pDbz1TgdqO5uTXWwmq8y/Q4oCJbUWDJEfzs1Bn+q22wgOxPP0wHkQfCy5rmCAyQacS/Y1ZxAMbNCj1+SYjsYmdZxbn5ydnQFLOdLeEDl6sMNLQhOzZKPLe4Qmj7qx3FuSufGyhFKslSKlfTV8VrC5oIHRjMsLRYmUSc2JlmvMx3Nk+OEygrNKK31tI7vjSOvk34sD3/1S77j+AQN2W8sgcADPKahGrsLnfGrwkMQqpml6gfikxAeZaWIg4/mQErcCIed7C1nW+LY46StXg0RWMcw/wyQChLsnE2owrf+u+FqKIUwlXb12HBETVnxcxkt1pn9secxc7zXE3Xm4C9gjl8CPzOFRS0DxbFrVk5+n0f9yBDDPbaowbR4N+CoRyhKSvGRHPGS4VTTlbxOFgg17FG25XTKDj6A4K3ToT4Smzn+CiN/8f5gOHF4SV+lcjFQNfn4kBIDS34YNGieKce15VNElU8O/xHUKkTMr1W6zKNA0kFoC2TUVBzQA1lzi43vNHlgCYBDeqekPPaAooNqaNSA99kguZYtaLlFqBJ0qjpHbc/RbiiP33wmO5taRaioK70iTk73A1UaxEqjyatGuF3Gu/69A69gWJ127il9JZqZm8NiQaLio+GIpeVjjMXWIHJXmAGMPnWhxrHkf+2PSf2RVQ7tViPfJWg4ZQ3wA4SudjAyi7xar6VoxLwuvIpX9jf5RV7qLi7OeCQjzJt4giOYUAqZxSIrGgXNVs9JSHpEsZFjTxbk5ISZgwszwsaPKrCRKPzpkVtCZq74Ajxk6TlprxKlbY/WF0oElnAJPnYQ0I7EamqVCmceG4YgltPIc0AlhchnmgBgj9c5nCpJNtqRzLDV4jmtHZq9u9kEZ/ZaveGvnDCDQd5w3u/HzIAX0DpXoV/0F/dzCTxiFwCru6mDqZ9cG/SsDlgvXZl4wsYfVSMI9G+dO2whhtn5hWnnvoUXtRGg3HsWCJRrzcjY6xG7RA1AfaOf3rhOlLoNB0x4p2zUFZiCZpvNOidvdrKg5LfdjJ99eo6E2R9USH9pawlQa42Tq+pyHlTZQMF6EMy6ynPZ15J9zNnFOKXLohl+CGciSS5p2ZW8aIdzvQ+a2NohdCs6TEmJlhFvkXc+H8HoL9+3LM83n8ueC//SIBAjXSWesl2SojgqjuWN3GhCHbpi0r6fPI3zd4JRbzV+C+seMTFkOykqHmHUS6yiRJyaPJB1FekojODh3aQ2K8cORxBdHCrOAtuEOJY/sB6o3iHbDYtaC+35s9IiAV2m/nPFvEjd7x3Rvfy3OTv5Qvp2e325uRE6UNP8UN5KrZCKR33f5kGqpJbnD9njDUwsEEXaVDnMnme3mNzoLYyBN8atkI/yk2gbe44NqPMW0ahIJUKmPjKyC1xe7pxBaDlXE/lMoEXJ64yHQ1eqpfaLY1nFVjxLS9iAJZJ4pVf4KFjvr+lkIb8TezyaG42ySIBgzabSzsIiwu7p333aodWW+/bM5V9Ei3lt8LA2JVJDsyuF97q6kLDDfXDGVmUR9ing9c62OV2rkVbiK7+U+FinrU5P1PAQAvFKK5ga8mMUxAr1gA9XypuAh43Zct//HwYo3xVBWwMl0jDD0ZXmev4F3+riBL3pWqZneGtHuG8iTJ4gTFw4FBhxUEeqXq96zhjmDsNrL61bDsjw+pS6jZWtG3K1uk/mUzoyUj7nLFnvvNsjlAgM18pAkZL2gyqoHXbpEWTY+ZeVmTDqFpN0lM0HC9hPrx4UJ+E6tmRRw76oBY2tfvSMM+KaHAXvAYxEMChpLel9IZfzuzVI5bZ5Fjcuf1p4i8XFW1zka65C8Bi/JwkEaKHw8vhNmraf885vKndMOvPblGkin6rQtVk3hdqOzM1SV1mfKklxYTn66n8bgTqoiIYZF+KYF9XQ6YtsKMzIu04+uY+WG5m3DN6NqE1fgT2G8tuTkstQh9vpGIY+a2OSJlsyF13Ss9oqtQv/zJ2LgKItyui3+fgGKhK0L/q73DhEhEcUvvGaPAfCExC63zDowL3iFhcfX/8Q+S5MlKFi0C7Rqga2Ex8gGQXOwghPwL3yEhqoTn9eBd/fx5uG/MtK/Kvp3hg/DLx9psDy8URUb6LFO9KVPnMK3g0fkzDB126MhxC+sFBz5fA5jREtpCyY8ypNyKGWgJgauPRTQcETZLTAIsZ3uUHuhkN/YdwJKw0FzLDuZen9kjfKzIwYdvEmyOwJIxisCjSmzQfgKKMZnnVcVJwAkzZEqCm6EKK+76DdS+nc5hYefbEatTBBPLN8KRqztVkFkUoWpkvPLzCfsTqGJnSvr6d91Qp1FBiZL9W0Msi0OCPeoMmBO+p2CPmwlRHwiPyRSvHIRWBl7BiPqwrWUr5iu7+9r45yUTFHzuYSJX/gOIi2Yx1T1w0txLB/34DKCUbXD5TLBzJzwzya+EgMM/FNsisSojq/SuNjApFvPfTvNnIUv5vwFIustJUVlVHNBK3ZSNq0HbhYiEu/V/SwIc1RBRwuZ9mVZXSLTmGdJt17cQeVvraSez+5FeZZGXQTyMDAr22Jnl4omMX3Z//mbIYf9TS1/exEN5hlDWL+C4GO5aEsFFyf7bA9racKvCMB2Rs5/v4nGPtKHbGXAIgG92QbKCswO6nczN1TZigm5/UptxEDl3Y9eFldEeSGMxTeEIQJ9VM8r8Nq7Np+wJkaMG8XOM6W9j19shrMKiqRci2N2pWHse4OAoJIyrZAOmuGj7zsaTVKZF8cV17Wy97l9MPWY5DCPr8po60pyJ+bZhqsMjMLxEvEZ2TOc/7PaWR75WopPaZV2pxdamGmCroFEPz6A5rF0ory/WiBFuzsBRa7IcHMTqRbseu20r06axS9DbbeiXBTJbUHLWWMETtue61zMX19bOmzF78dvyRhnoR1wxaI5UCoFT2S3SoT93kqZ38Mgwts3yK5hirzyIRx/jtM78F7Kpayqx6fV6ULfLONJMfxL7atmPadix9q5bljR0nAElggzwRAR2fCC/yVMtC8mLMlR0JZd+Bwp4Fz+b6fWYCjkMo3uuJtprvcdXzIvxJEyHdqaAPhRgFRuxBXstnqfWygefMqZ/Le5DA2seqnrP2o+iateDpP9KpQrvWPnMLjlARlEc7NPcWDd/0X1xFdW3VJBVqXMIs6EpH2Ao8m1EJr9infDpRQ5DKj+OZSUDGSktFSWbi4/7bmrkaKmE9I8+1k4oDE826+Vlr90MW79/k5FoLfBy7KFBs+mwx2fLnFgQiTNxqVhEOYyLILeZrYVDoa7Y5NT4g94Xa6ODOwN3uLIJOBdfZedw4SKyicmOaiKOnGeA+RZbvpNykoECENGvFYzmigyuTVBoZQy0fK86SWYGD+Eotbq1WH9fdCTBLR/KIbNqZINYrA0cDwvxIfZ/mKgdXyI9FZayBt+89uFH8QsIlRf+8NTTvdMkW7x4JFUit2o/s3QQBknPwa2B0b41KfR9RRua6qhQ5A5H0AMiDOskyZlH5P+rNERnpZAshFRpaIdrrKQnzJ1L9IKCiXVCfyh4hvYpYOAXwaZF+w4+3ZxGSA1Vdpqc4S96Agt1ROqa2htLRxMvosI8DcwrqtdfoHSlErMykAh/s8FcbEYdb1yItQLGPFjN8y3B2zdAldgV8Kni8mk5L4N2IlVPDrWPEVQonFpGQ1fPk7B56KrXWE+XUKrYKjG7EZD4UN89DU4kvDHPJvNNQ69UmqbHn2WAlfr4d0P3ptOcr5db/pdlxKFBqeLJhVWFRN8r+yLNlymKHFnbUjKL73yjxM3L5Fl78H3A7+MZ3AaOAxR7aVzsElh/itU+TfjqT0SgmBksS+sdtYaCjyKDfaBYn6TI6zCGsFYInk25A/C267iblkvbAXSkvl/6bK6zJMhf9A89QzsgLAi7CP44ZRzbDHKLm9UHNu1M+uIvGdxnzaeErjzBqU2nU5+VmmFub+4hKWsrCFOhdtJ9gckuylM116OEvTgm89ffMrtcNoeiwOYet1m04E4ih/Itp2MHrKEPUjtqwI+eRG+8BcEmGGEy2w4gIK7Vbzbb3lMRf6E9wcmC9ldkHAwG6FDFKM9G+QrhTuDK0aM10SYKB6Lu6DcmZbbPWfkfceX/Rn6DNuNQ+bvN1ZbdNMdHce7KbAaU6nQD6LkInV3YEo/fj5hUmGxSxhfvjTbC55f9ThzRDFd6G+MPqWJiu+VKvgMkHyDBKf+4quGuAalHk3Yg56v67e8nNQkcvxsxzqfbTe3Dt7RSw+316s6sJfGRqgLQ40GM4G9PQtSm1ETkGaRzsQaIwTbi5PAXcLUZ3Vrt3sKjuiihzlkufNYr87mYmsjJmIYcnyaksCtxONkbj/rkvHkjZp8l7yl+f+uiFo27Ppl/Ff+BEPGZJ78tc9q4tj7AIVeyOpFYRd3Atb7YZ9lOInrXYQqgUjFDl0m/64p2aPg/TWIZBV++7OubVYBZJ5TqIzAttP29wQf/lByviSDW1sdMlUzFcucQ7YUA9ix0ZMIUnNzd/FClQsbB4xpGA7Rb4eGd/VVe+BHm0AtfTKtC8CPnZLm5pmUH4OpfT98LI174aRv1Sv5BueNabBQHWA0O4ULUdBhCp5+wGasiSU1nq7MruVW1G6lL0GZXSeJ5T2MLVKuzQsE1fXmb5mtROcMMPfJYw62JZDn5OTrP+ONM8wYnOfSc3dVfbNDFl8hDaRlebNg2t1kjV+IywssJrHcRugyN8aCqzcFXqTBcm2ncyjcYgFR0VFV6HYM6U7by/4eDeorP96wSxza1L78G1Xi3zYbSX46QBMorqpEqtRvdLmJ/Qtf15LXOc3DpocgyfkOoB/M4LAgE/lol3BJ5iJBNwVaWq+0A0MMrt+RQqrgC1c5gCI7Q/P7qebIeN45Fq9Sbj5/KZK6sPFTQZWCxC3L9XoUiwlfrDlvrKSYywRLrYDupmrinhKaQSSjXkqbXACNt7g+4ePkRxMg205R2K2SJucuo09j9qSEeNjGF3KVJJVTzt1c5Gm8ydFn9rAhAXljnMP0rTBhjIP55c39S1cxwEAyaTdL2L9ImonJlUBVHuU2/WjST82xF6e5uKEqfBSV3O9ySgFmPFXcpycXx0H3FfWb2EVBlVwoY6WiaBRKkFdb/ePO2nbYzd9+eSs/X1o6I2gEL7CCA1xP/x93+SK7Xk0mf51jGIAgVDvSoZ+72WiQ9LISiB/OjBgyuAIAs9G9FGcnHLhKoo9nNZw0KfFfy69waOJGiJ6T36YBrBI0c7Qh8c4LU40RqqamEFjZoRQdX5cCJY3aphhFH2RiSDxrs08xDlspYAuLtr38uLKgBZdSqZbzxtoVnbYJfARs0GBrwgtweMYTKO2YbLGn2nbUShPINX8KDQ2EeddaGbnhtHWfBGomWXhz0g69kiYs4UDmCjM/BIJ+K8L/GiSVKQ5NabfDeJat3bvyg5Vm6K9gZxMkPMVCrfO+MST5LD1mFqBuAoP5CS+cI6z4Q6I2WNlzoDj7/awQRTjQgNN0wILQv5PME+ct2YMXUXdkhQMEY7Zb0QII2uCkGOO/DH11VMK6duUq2qkaqjMXCYC6wDfwp3ngSFDohtR1hpUU69A4evtvIHDhPLx9DLogxTLYwCYBYkvm87K61JK1BsERsR6uEG/eIgf6sI7HocdkdziGNDMzsVqKus1sqed7CROJ4EaCCewKPZt6Ee7etrRUAi+Li5UwnUBmIe9KrHFB14H3prqHFwlsnWbxeVb7aCX+PeceIKVQa1oKJmSoSB63j7/a3EerGDVmY2HVZEuRQvQZvej+5kjimDn049a9iuRokmd2Q0IVA98UTqUyHgZKuAExulbsqJMZHVQtGN1WVDExbWBkg/nRPrCbRT3zJQy+0mDQF+K5P0TvYkPu3APIK1V8irvCdCJg2AQBb/avCqlTthSP4hLcFat38XZ2IFll6Zm1qRdIXAD7/YooAhwxYkoOBnj1LIgVg1gL6DENQpiMWm/Uf/RfbfCS7oJ82hFADGWi39aUVLqSE735u8obwVK0VmvVh0joNxPvHfoAdcO2ApoeX3cuPSdHM8wAHb9YBsbcyCTgN+c3FhrMbyltKKDUBMCL/DL+D3EmzDdqTtgH11A32tdc2D16an0H179ejnXBGFg0nOXLyfr/8nvZ+KeE6/qmCFaZu8+sjaptno+QvXc2N+DvH0GusxQUHHWnGXMIezdUwuBcOnxlV4TmhElp0PRtoqNGFAz5DiI66MJ+VcgrA7Sl3X4jotVpZ2rzXGWAL7QqhYbHvIkc1W1695bu2aC3LmPYQc0aUbvWreoorLViWJ6MUlwtq1MLrn3DFG3O40msJ9Kn0CZchVc8D6SrNfzYTePAX0L4ZMoYXzZa5ndQbbW61t4WV8hA1YwEOWxtYIyWtlDRT25X354tjTkmkhQDAcZ6XVlUrsyqwa6rNWpxfkQFm3iANoc9dw0KmB7xjnBVZav74IkDA2q34YNweiujJdYoPOxXArNMTdw2ktuZFLaWuU8KqZlNna4jpETPJICCxCd8Oz8MaXbCtE+BAQMaZX6tWANfE+G0YIhUR3k+7x3899N/CGHCja5T9H+DEMajCmRFNWtx0pPHGaY+oz+9+LCH9kj/9iQJn6qAPoT1gmG17V40+NEas1+pCGMIbdZB+aqqPqO21f2TRNpH15C8oqYw4kC8YZqNd8yztg21arqrhKArx29BQKWY6xH4ueJSFuWvi0EzjQU4McVUxhzZqEQR7ZOMcbf1o2VbeEseC+fsdqXZ7kZgky6akrzmmv9ahqQ4tE9iQDUstm4sVv/v86KXuNlGUKAkvYeXM4qCH6V6R+TLOYPGjWuVXRoHFDXjNyx7WmlbX8CNIN7MShPwt44C6Vj0Xrc0+67OcH2+hLARb1PBNdkSIcOn50Y3gb7csn9b2fRUGN2xeVdJUjI1OE8NeNCE9GSfyuaM6IAKftqH9LLqtbsmH+eRJXqC+iZOCksx1ocU5e4NyC62nz4+R3HXDAzo8ZCD7nq8gQBClinM/CPGB51gkxDa28HsHArdXKtTdPXfOgoypJ2Ge1MxpxovUJ9sJmqEn/6IAhabAoaByLAwI2tEbThQ27C8Gmy9CG4Q2eavMvB1WQwFSQcVeWQvL2B+AtSYgkGU6ta5mRCCjvUOs9k4CxLAP8+xfpUAUqYUFHIM9xJOc7OQqh2LnQDH5/s1bcuH1KvQ4L7oBEXumfL4Ma36X8rg8pFj9v1srfQfaEtAw8tXTHSq9RKCxcHlmDGyLLXQbMecA6HE9vgH6EL0TWgYVnhNSN4QWrvfmeunwz7k/8/Cc5qDlO2QgBY+3wpxufQ4SxOUqZ/A2a7lCgMYUxU3DXX4V2gs+xzJlyYxdruF/zInpi4P7BvYf33F7CylEfQm82RnHZlz1wtVz8Yk9DuQPfSN8jhl2Abp1fHtesbTDP8yl704hwdlqHlc0HRFiy0k8BEnnLEE2vyNvBrBJG0uF2lXSIHTMJzXLu6hMUMJVejJu3zHkYE1voltZbEvp0pJRrxa6ghVBPw0SoH+QTcUA/YosYMu4A4plRouN230VnchnlqaiGjBMRwk5kdQ/qfAvmDcze61Xr/vIbN9DXcHVTi8XlZaqjt4RXXuw592yLnKWZrOG70XJsbpyeBKYyCr6dfd+OEUyCVtC3uPEiyAhPcvL0EzIf1BjlndDAb1vcE1hGb3m7iHjJYoXMIlsydqI7yZm87kG9kHh/dlgRlvgkCpkudrSuqVBITD37EvbWvgF7ej+zQjxEgfmUE4GtXzUlAv9Nk0QlDXVzrxrUo7H3SlzbnVAUFXWw8EhMPD3cdc286xVmdBkkXOtOk9A2egtsdsA9pL0h9dxPJsM7VQ7+5T7DuIn2ut/sW9BH+vaf3O/vEjGDSQgeq9XzA7QNX4sQt6kCWy7f6otmfEKCZ9mn1qbeb9Rsl1rkZgpousQvIaQgZGtBVqf2++bwyeMWhX4WCWlPfxMuoNCFHgO+t6u2a9nPS322MwaDL99QfoY9vF9hC6npW25aZVc2Siu3+VdvN6E7uHbE238CRj+y8khO5klnovKPm9+kQ38IQ00O8q11lnekCWixtHlF9nQZkOwZv1lKEOd7cIAoNpxpNSZXBYMI0kNqR5cF/W6FDdz60HbARBllYEMM4nTk5+09EwghZHoyfeNE9XCd8C1MdSZYHyqVUg/6QfXUsWyRaf62Yv7iS+kyQRqE4tKyoYTSvQpwHpuTd0YOBGSQo7IZByqsL1qUq2EPAL4+V9JITGng9wyRyg4j7gqOpjNqSbkOlwYidCZPOedZvY0/0mhFeFmcqnHQLo/xYfZFS6ZJCCpgHNyDtH7vLitvue+iLeKPdALb/O0OhjD1dBlMN+sUUSkkWlnBgHcpPC0/2q3Yyh6j921flnXjiu6Rn94ouEyyunlj5a4LjclRIyyEZ8DM5ST+dov/LzHt3+7hWbKcqNZLnd1E+C04dVbq7eEVpQ66cRRtt9L7QTWNnseRymaw4AagCR05r3jMIVMEnYUJjSDUpd1e7WTOLRpoUjGX6geaIXC+2sBeVeWHDVrCbH56J/WJf8hw5HVgGI1G/TZ7dfv9+9aqVXTHHnOQfOpUL2SK5osVpRsXtf5DEBr6BQvhby2QMn6h2/viNFl5nU7Wf4ed+th8TfMiflFeGVBdOpRCrjC3Ky9L8iRncFi5EIm8dJ4I/0uwAUHeddFXehnIqWArXbqudUBiG41q7/ql7CAUJRfktjeErAt7bQOW5XNodn+4fI3P0ychnS9OCrxTXV3bZJyw1ub/0Es8pB2DcSYtI35t+3pvj2unSPNaXiKuc82/rkJp3GB1ZMuaOAA/nXiTXfgBxbz82aoFrfswZiqXkvOqcwM/RpG/55uz5kMyr/vNDzRyoYuFpNDZznkRs13X8iyjm1cHqZ5Jmlbz+K59u8D+YFoICKUZxhxfaQdjV0pICqhr3pVWHcf9EgLuMWVr9VvX3QiBk4E/W6V1srtyM9vrXleWduhJGJ0+n0dgaEDwYh5+D1bDkB+MisRw5bwQBVIfQNhPlMW7GCCJ6BhQWNPCR2MFtqL87u0gn+OQrx4gFLgzK8Aqigyrr6V0I0UiHDzzRceBPMkLfZKK/DYVEiLA9wUfWWYePf7dYEl/QcLcdAyfsS/2bZBBaekE53f04ExE/sBmB5GEcMyy4+Y+bDwA+TSFqgmz0CGPGwIXHlT0M9A8z4xkVZAQsqZii3AWl9Jn5NT1jkFtGmBwTnPpvX+QuU/A/TTZ96Ms3yqRwAIwIpmw6WLBKZxAG3OYqksMtc1SMYcGkwYA93AMwvlMve8xmhbaKz5ZSLuMZ7/88BxZuDeCR8Mlait8RBoP3M7S7ASmtXS5pqmCmOUeIEOVvec9XKXagam6ojfmiocoKyqjxB0G2HTBYGxdMdsTJvCmMk/P0sfogLbZ7lhkOko/yLphGpfAEd2nyBIrUhSIahCGDtjkdxK++X2sfbWx/BiliboqhuG/Jiwba2NfqJuNL1E5904X5JuxzS8COimvD5X2O8KoLom9U3renI2iRGAyRt6q6hbIkqQDN4opPSKDOAvC9iwIorucBGk/Np/zAJ7KR6HKBV5oPY8nLT8O4Q/zxGIMg1H7O2WRPhjUU/fVvJ21oyuFbMw1MqSpdtZYBc9Zr+hyzrxbC71OhtcGyChA6H3vTheHHqoMbkz7ZCs/op2fqLIqwuOwt84SPVY8O+U+io514MBqUMz8evhU+7Eu3XYpRNeCMS5zPWmqWQPF3+K/QKxOxxpfXfBeUu06UCuEneOzpZWk2JeBwb4Eyus8U3ADvdSVLZJkrHJU0VdIcxS1h/VOMfdFRW0Ki5HBSgOM52+I+70Gk10RDfX2hQM17uS8xcRCjtrvMQQEpMgReO5lPvSR/ZLVfikUfL6A7DRE1mwAX8KCOIVgfBb7XjDB4uzk7/Mq4CKrdedvi2u3P5e2+Tlj10YZe0WYjbLCTVUU2JcKaNiLN3Jyql3VeAymncDJeAEGISepdxs6hXL4fM=', 1);
INSERT INTO `PAPER` (`NAME`) VALUES ('ADMIN');
INSERT INTO `AUTHXENTERPRISE` (`AUTHID`, `ENTERPRISEID`) VALUES (1, 1);
INSERT INTO `PAPERXPERMISSION` (`PAPERID`, `PERMISSIONID`) VALUES (1, 1),(1, 2),(1, 3),(1, 4),(1, 5),(1, 6),(1, 7),(1, 8),(1, 9),(1, 10),(1, 11),(1, 12),(1, 13),(1, 14),(1, 15),(1, 16),(1, 17),(1, 18),(1, 19),(1, 20),(1, 21),(1, 22),(1, 23),(1, 24),(1, 25),(1, 26),(1, 27),(1, 28),(1, 29),(1, 30),(1, 31),(1, 32),(1, 33),(1, 34),(1, 35),(1, 36);
INSERT INTO `AUTHXPAPER` (`AUTHID`, `PAPERID`) VALUES (1, 1);

# END SEED;

SELECT * FROM CODE;