CREATE USER 'TEST_USER'@'%' IDENTIFIED WITH mysql_native_password BY '[PWD]';

GRANT SELECT ON ERP_OPTICA.AUTH                 TO 'TEST_USER'@'%';
GRANT SELECT ON ERP_OPTICA.AUTHXENTERPRISE      TO 'TEST_USER'@'%';
GRANT SELECT ON ERP_OPTICA.ENTERPRISE           TO 'TEST_USER'@'%';
GRANT SELECT ON ERP_OPTICA.AUTHXPAPER           TO 'TEST_USER'@'%';
GRANT SELECT ON ERP_OPTICA.PAPER                TO 'TEST_USER'@'%';
GRANT SELECT ON ERP_OPTICA.PAPERXPERMISSION     TO 'TEST_USER'@'%';
GRANT SELECT ON ERP_OPTICA.PERMISSION           TO 'TEST_USER'@'%';
