CREATE VIEW VW_USER$PERMISSION AS (
	SELECT 
		P.PAPERID,
		A.AUTHID,
		P2.PERMISSIONID,
        E.ENTERPRISEID,

        P.NAME,
        P2.PERMISSIONNAME
		
	FROM       AUTH             AS  A

	INNER JOIN AUTHXENTERPRISE  AS AE ON AE.AUTHID          = A.AUTHID
	INNER JOIN ENTERPRISE       AS  E ON  E.ENTERPRISEID    = AE.ENTERPRISEID

	INNER JOIN AUTHXPAPER       AS AP ON  AP.AUTHID         = A.AUTHID
	INNER JOIN PAPER            AS  P ON  P.PAPERID         = AP.PAPERID
	INNER JOIN PAPERXPERMISSION AS PP ON PP.PAPERID         = P.PAPERID
	INNER JOIN PERMISSION       AS P2 ON P2.PERMISSIONID    = PP.PERMISSIONID 

	WHERE
				A.DELETED_AT IS NULL
		AND  AE.DELETED_AT IS NULL
		AND   E.DELETED_AT IS NULL
		AND  AP.DELETED_AT IS NULL
		AND ( P.DELETED_AT IS NULL AND P.ACTIVATED = 1 )
		AND  P2.DELETED_AT IS NULL
);