DROP USER 'AUTHORIZATION_USER';
CREATE USER 'AUTHORIZATION_USER'@'%' IDENTIFIED WITH mysql_native_password BY '[PWD]';

GRANT SELECT                    ON ERP_OPTICA.AUTH              TO 'AUTHORIZATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.AUTHXENTERPRISE   TO 'AUTHORIZATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.ENTERPRISE        TO 'AUTHORIZATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.AUTHXPAPER        TO 'AUTHORIZATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.PAPER             TO 'AUTHORIZATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.PAPERXPERMISSION  TO 'AUTHORIZATION_USER'@'%';
GRANT SELECT, INSERT, DELETE    ON ERP_OPTICA.PERMISSION        TO 'AUTHORIZATION_USER'@'%';
