DROP USER 'AUTHENTICATION_USER';
CREATE USER 'AUTHENTICATION_USER'@'%' IDENTIFIED WITH mysql_native_password BY '[PWD]';

GRANT SELECT                    ON ERP_OPTICA.AUTH              TO 'AUTHENTICATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.AUTHXENTERPRISE   TO 'AUTHENTICATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.ENTERPRISE        TO 'AUTHENTICATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.PERSONCONTACT     TO 'AUTHENTICATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.CREDENTIAL        TO 'AUTHENTICATION_USER'@'%';
GRANT SELECT                    ON ERP_OPTICA.PERSON            TO 'AUTHENTICATION_USER'@'%';
GRANT SELECT, INSERT, DELETE    ON ERP_OPTICA.CODE              TO 'AUTHENTICATION_USER'@'%';
