CREATE USER 'M2_USER'@'%' IDENTIFIED WITH mysql_native_password BY '[PWD]';

GRANT SELECT, INSERT, UPDATE    ON ERP_OPTICA.PERSON                TO 'M2_USER'@'%';
GRANT SELECT, INSERT, UPDATE    ON ERP_OPTICA.PERSONDOCUMENT        TO 'M2_USER'@'%';
GRANT SELECT, INSERT, UPDATE    ON ERP_OPTICA.PERSONCONTACT         TO 'M2_USER'@'%';
GRANT INSERT                    ON ERP_OPTICA.CONTROL               TO 'M2_USER'@'%';